dist: trusty
language: ruby
rvm:
  - 2.4

addons:
  postgresql: 9.4

env:
  - DATABASE_URL=postgres://postgres:@localhost/test

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
